apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samanespring
  template:
    metadata:
      labels:
        app: samanespring
    spec:
      containers:
        - name: samanespring
          image: kanee/samanespring:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/samanespring
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  selector:
    app: samanespring
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort  # Changement du type de service de LoadBalancer à NodePort
